// Chart.js Documentation: https://www.chartjs.org/docs/latest/api/
// Chart.js Classes
export {
  Animation,
  Animations,
  animator as Animator,
  ArcElement,
  BarController,
  BarElement,
  BasePlatform,
  BasicPlatform,
  BubbleController,
  CategoryScale,
  Chart as ChartJS,
  DatasetController,
  DomPlatform,
  DoughnutController,
  LinearScale,
  LineController,
  LineElement,
  LogarithmicScale,
  PieController,
  PointElement,
  PolarAreaController,
  RadarController,
  RadialLinearScale,
  Scale,
  ScatterController,
  TimeScale,
  TimeSeriesScale,
} from "chart.js";

// Chart.js Interfaces
export type {
  ActiveDataPoint,
  ActiveElement,
  AnimationEvent,
  ArcBorderRadius,
  ArcHoverOptions,
  ArcOptions,
  ArcProps,
  BackdropOptions,
  BarControllerChartOptions,
  BarControllerDatasetOptions,
  BarHoverOptions,
  BarOptions,
  BarParsedData,
  BarProps,
  BorderOptions,
  BorderRadius,
  BubbleControllerDatasetOptions,
  BubbleDataPoint,
  BubbleParsedData,
  CanvasFontSpec,
  CartesianParsedData,
  CartesianScaleOptions,
  CartesianScaleTypeRegistry,
  ChartArea,
  ChartComponent,
  ChartConfiguration,
  ChartConfigurationCustomTypesPerDataset,
  ChartData,
  ChartDataCustomTypesPerDataset,
  ChartDatasetProperties,
  ChartDatasetPropertiesCustomTypesPerDataset,
  ChartEvent,
  ChartTypeRegistry,
  CommonElementOptions,
  CommonHoverOptions,
  ComplexFillTarget,
  ControllerDatasetOptions,
  CoreChartOptions,
  CoreInteractionOptions,
  CoreScaleOptions,
  DatasetControllerChartComponent,
  Defaults,
  DoughnutAnimationOptions,
  DoughnutControllerChartOptions,
  DoughnutControllerDatasetOptions,
  DoughnutMetaExtensions,
  ElementOptionsByType,
  ExtendedPlugin,
  FillerControllerDatasetOptions,
  FillerOptions,
  FontSpec,
  GridLineOptions,
  InteractionItem,
  InteractionModeMap,
  InteractionOptions,
  LabelItem,
  LayoutItem,
  LegendElement,
  LegendItem,
  LegendOptions,
  LineControllerChartOptions,
  LineControllerDatasetOptions,
  LineHoverOptions,
  LineOptions,
  LineProps,
  ParsingOptions,
  Plugin,
  PluginChartOptions,
  PluginDatasetOptionsByType,
  PluginOptionsByType,
  Point,
  PointHoverOptions,
  PointOptions,
  PointPrefixedHoverOptions,
  PointPrefixedOptions,
  PolarAreaControllerChartOptions,
  PolarAreaControllerDatasetOptions,
  RadarControllerDatasetOptions,
  RadialParsedData,
  RadialScaleTypeRegistry,
  Registry,
  RenderTextOpts,
  ScaleTypeRegistry,
  ScriptableCartesianScaleContext,
  ScriptableChartContext,
  ScriptableContext,
  ScriptableLineSegmentContext,
  ScriptableScaleContext,
  ScriptableScalePointLabelContext,
  ScriptableTooltipContext,
  Segment,
  Tick,
  TickOptions,
  TitleOptions,
  TooltipCallbacks,
  TooltipDatasetCallbacks,
  TooltipDatasetOptions,
  TooltipItem,
  TooltipLabelStyle,
  TooltipModel,
  TooltipOptions,
  TooltipPosition,
  TooltipPositionerMap,
  TypedRegistry,
  VisualElement,
} from "chart.js";

// Chart.js Types
export type {
  Align,
  AnimationOptions,
  AnimationSpec,
  AnimationsSpec,
  CartesianTickOptions,
  CategoryScaleOptions,
  ChartComponentLike,
  ChartDataset,
  ChartDatasetCustomTypesPerDataset,
  ChartItem,
  ChartMeta,
  ChartOptions,
  ChartType,
  Color,
  DatasetChartOptions,
  DecimationOptions,
  DefaultDataPoint,
  DoughnutDataPoint,
  EasingFunction,
  ElementChartOptions,
  FillTarget,
  InteractionAxis,
  InteractionMode,
  InteractionModeFunction,
  LayoutPosition,
  LinearScaleOptions,
  LogarithmicScaleOptions,
  Overrides,
  ParsedDataType,
  PieAnimationOptions,
  PieControllerChartOptions,
  PieControllerDatasetOptions,
  PieDataPoint,
  PieMetaExtensions,
  PointProps,
  PointStyle,
  PolarAreaAnimationOptions,
  RadarControllerChartOptions,
  RadialLinearScaleOptions,
  RadialTickOptions,
  ScaleChartOptions,
  ScaleOptions,
  ScaleOptionsByType,
  ScaleType,
  ScatterControllerChartOptions,
  ScatterControllerDatasetOptions,
  ScatterDataPoint,
  Scriptable,
  ScriptableAndArray,
  ScriptableAndArrayOptions,
  ScriptableAndScriptableOptions,
  ScriptableOptions,
  TRBL,
  TextAlign,
  TimeScaleOptions,
  TimeScaleTickOptions,
  TimeScaleTimeOptions,
  TooltipPositioner,
  TooltipPositionerFunction,
  TooltipXAlignment,
  TooltipYAlignment,
  TransitionSpec,
  TransitionsSpec,
  UpdateMode,
} from "chart.js";

// Chart.js Values (constants, plugins, etc.)
export {
  Decimation,
  Filler,
  Interaction,
  Legend,
  SubTitle,
  Ticks,
  Title,
  Tooltip,
  defaults,
  layouts,
  registerables,
  registry,
} from "chart.js";

// React Chart.js 2 Documentation: https://react-chartjs-2.js.org/components
// React Chart.js 2 Components
export { Chart, Bar, Line, Pie, Doughnut, PolarArea, Radar, Scatter, Bubble } from "react-chartjs-2";
